pool:
  vmImage: macOS-10.15
trigger:
- buildbranch_osx
pr: none
stages:
- stage: stage_0
  jobs:
  - job: stage_0_job_0
    steps:
    - script: |-
        \
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-galactic-rosbag2-compression-zstd ros-galactic-ros-base
          ros-galactic-rqt-common-plugins ros-galactic-desktop
      displayName: Build ros-galactic-rosbag2-compression-zstd ros-galactic-ros-base
        ros-galactic-rqt-common-plugins ros-galactic-desktop
