package:
  name: ros-galactic-ros-base
  version: 0.9.3
source:
  git_url: https://github.com/ros2-gbp/variants-release.git
  git_rev: release/galactic/ros_base/0.9.3-2
  folder: ros-galactic-ros-base/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-galactic-ament-cmake
  run:
    - python
    - ros-galactic-geometry2
    - ros-galactic-kdl-parser
    - ros-galactic-robot-state-publisher
    - ros-galactic-ros-core
    - ros-galactic-rosbag2
    - ros-galactic-urdf
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
